### ISSUE TITLE
Failing test in AcceptanceSpec after upgrade to micro-infra 0.8.1

### ISSUE THREAD

**Issue by szpak** [4finance/boot-microservice#26]
After upgrade micro-infra to 0.8.1 `should find a place by verifying tweet's coordinates` in `com.ofg.twitter.places.AcceptanceSpec` fails with:

```
com.jayway.awaitility.core.ConditionTimeoutException: com.jayway.awaitility.core.ConditionFactory.untilAtomic Callable expected "\n                                                                            [{\n                                                                                    \"pair_id\" : 1,\n                                                                                    \"tweet_id\" : \"492961315070439424\",\n                                                                                    \"place\" :\n                                                                                    {\n                                                                                        \"name\":\"Tappahannock\",\n                                                                                        \"country_code\": \"US\"\n                                                                                    },\n                                                                                    \"probability\" : \"2\",\n                                                                                    \"origin\" : \"twitter_coordinates_section\"\n                                                                                }]\n                                                                            " but was <[
                       
                {
                    "pair_id" : 1,
                    "tweet_id" : "492967299297845248"
                     
                        ,"place" :
                        {
                            "name":"Washington",
                            "country_code": "US"
                        },
                        "probability" : "2",
                        "origin" : "twitter_place_section"
                    
                }
                
                   ]> within 2 seconds.
	at com.jayway.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:96)
	at com.jayway.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:87)
	at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:590)
	at com.jayway.awaitility.core.ConditionFactory.untilAtomic(ConditionFactory.java:548)
	at com.ofg.twitter.places.AcceptanceSpec.should find a place by verifying tweet's coordinates(AcceptanceSpec.groovy:65)
```

It works fine with .0.7.7.

**Comment by nurkiewicz** [comment]
No longer fails.
