### ISSUE TITLE
Acceptance tests still fail on Travis (sometimes)

### ISSUE THREAD

**Issue by szpak** [4finance/boot-microservice#35]
From current master:
```
com.ofg.twitter.geb.HealthEndpointUISpec > Setup step FAILED
org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
Command duration or timeout: 338 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'testing-worker-linux-e7a62211-1-21232-linux-13-50406087', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-042stab090.5', java.version: '1.8.0_31'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=31.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]

Session ID: db6420dc-750d-44f5-a15e-7ab4f9b88eeb
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
at geb.navigator.NonEmptyNavigator.click(NonEmptyNavigator.groovy:455)
at geb.content.TemplateDerivedPageContent.click(TemplateDerivedPageContent.groovy:113)
at com.ofg.twitter.geb.HealthEndpointUISpec.Setup step(HealthEndpointUISpec.groovy:27)
Caused by:
org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'testing-worker-linux-e7a62211-1-21232-linux-13-50406087', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-042stab090.5', java.version: '1.8.0_31'
Driver info: driver.version: unknown
```

@thiefik Do you have idea what else could be wrong after the last enhancements?

**Comment by thiefik** [comment]
I will take a look on that.

**Comment by szpak** [comment]
There weren't errors of that kind recently, so your fixes @thiefik seems to be enough. Thanks.
